// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Car struct {
	ID           string    `json:"id"`
	Model        string    `json:"model"`
	RegisteredAt time.Time `json:"registeredAt"`
	User         *User     `json:"user"`
}

type Group struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Users []*User `json:"users"`
}

type NewCar struct {
	Model        string    `json:"model"`
	RegisteredAt time.Time `json:"registered_at"`
	UserID       string    `json:"userId"`
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Age    int      `json:"age"`
	Groups []*Group `json:"groups"`
}
